/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteRouteImport } from './routes/_authed/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedAccountRouteImport } from './routes/_authed/account'
import { Route as AuthedAdminRouteRouteImport } from './routes/_authed/admin/route'
import { Route as AuthedMasterRouteRouteImport } from './routes/_authed/master/route'
import { Route as AuthedAdminIndexRouteImport } from './routes/_authed/admin/index'
import { Route as AuthedMasterIndexRouteImport } from './routes/_authed/master/index'
import { Route as AuthedAdminFridgesIndexRouteImport } from './routes/_authed/admin/fridges/index'
import { Route as AuthedAdminSalesIndexRouteImport } from './routes/_authed/admin/sales/index'
import { Route as AuthedAdminSalesSaleIdRouteImport } from './routes/_authed/admin/sales/$saleId'
import { Route as AuthedFFridgeIdIndexRouteImport } from './routes/_authed/f/$fridgeId/index'
import { Route as AuthedMasterAdminsIndexRouteImport } from './routes/_authed/master/admins/index'
import { Route as AuthedMasterFridgesIndexRouteImport } from './routes/_authed/master/fridges/index'
import { Route as AuthedMasterSalesIndexRouteImport } from './routes/_authed/master/sales/index'
import { Route as AuthedMasterSalesSaleIdRouteImport } from './routes/_authed/master/sales/$saleId'
import { Route as AuthedFFridgeIdProductProductIdRouteImport } from './routes/_authed/f/$fridgeId/product.$productId'
import { Route as AuthedFFridgeIdSaleSaleIdRouteImport } from './routes/_authed/f/$fridgeId/sale.$saleId'

const AuthedRouteRoute = AuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedAccountRoute = AuthedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedAdminRouteRoute = AuthedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedMasterRouteRoute = AuthedMasterRouteRouteImport.update({
  id: '/master',
  path: '/master',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedAdminIndexRoute = AuthedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedMasterIndexRoute = AuthedMasterIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedMasterRouteRoute,
} as any)
const AuthedAdminFridgesIndexRoute = AuthedAdminFridgesIndexRouteImport.update({
  id: '/fridges/',
  path: '/fridges/',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedAdminSalesIndexRoute = AuthedAdminSalesIndexRouteImport.update({
  id: '/sales/',
  path: '/sales/',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedAdminSalesSaleIdRoute = AuthedAdminSalesSaleIdRouteImport.update({
  id: '/sales/$saleId',
  path: '/sales/$saleId',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedFFridgeIdIndexRoute = AuthedFFridgeIdIndexRouteImport.update({
  id: '/f/$fridgeId/',
  path: '/f/$fridgeId/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedMasterAdminsIndexRoute = AuthedMasterAdminsIndexRouteImport.update({
  id: '/admins/',
  path: '/admins/',
  getParentRoute: () => AuthedMasterRouteRoute,
} as any)
const AuthedMasterFridgesIndexRoute =
  AuthedMasterFridgesIndexRouteImport.update({
    id: '/fridges/',
    path: '/fridges/',
    getParentRoute: () => AuthedMasterRouteRoute,
  } as any)
const AuthedMasterSalesIndexRoute = AuthedMasterSalesIndexRouteImport.update({
  id: '/sales/',
  path: '/sales/',
  getParentRoute: () => AuthedMasterRouteRoute,
} as any)
const AuthedMasterSalesSaleIdRoute = AuthedMasterSalesSaleIdRouteImport.update({
  id: '/sales/$saleId',
  path: '/sales/$saleId',
  getParentRoute: () => AuthedMasterRouteRoute,
} as any)
const AuthedFFridgeIdProductProductIdRoute =
  AuthedFFridgeIdProductProductIdRouteImport.update({
    id: '/f/$fridgeId/product/$productId',
    path: '/f/$fridgeId/product/$productId',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedFFridgeIdSaleSaleIdRoute =
  AuthedFFridgeIdSaleSaleIdRouteImport.update({
    id: '/f/$fridgeId/sale/$saleId',
    path: '/f/$fridgeId/sale/$saleId',
    getParentRoute: () => AuthedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthedAdminRouteRouteWithChildren
  '/master': typeof AuthedMasterRouteRouteWithChildren
  '/account': typeof AuthedAccountRoute
  '/admin/': typeof AuthedAdminIndexRoute
  '/master/': typeof AuthedMasterIndexRoute
  '/admin/sales/$saleId': typeof AuthedAdminSalesSaleIdRoute
  '/master/sales/$saleId': typeof AuthedMasterSalesSaleIdRoute
  '/admin/fridges/': typeof AuthedAdminFridgesIndexRoute
  '/admin/sales/': typeof AuthedAdminSalesIndexRoute
  '/f/$fridgeId/': typeof AuthedFFridgeIdIndexRoute
  '/master/admins/': typeof AuthedMasterAdminsIndexRoute
  '/master/fridges/': typeof AuthedMasterFridgesIndexRoute
  '/master/sales/': typeof AuthedMasterSalesIndexRoute
  '/f/$fridgeId/product/$productId': typeof AuthedFFridgeIdProductProductIdRoute
  '/f/$fridgeId/sale/$saleId': typeof AuthedFFridgeIdSaleSaleIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/account': typeof AuthedAccountRoute
  '/': typeof AuthedIndexRoute
  '/admin': typeof AuthedAdminIndexRoute
  '/master': typeof AuthedMasterIndexRoute
  '/admin/sales/$saleId': typeof AuthedAdminSalesSaleIdRoute
  '/master/sales/$saleId': typeof AuthedMasterSalesSaleIdRoute
  '/admin/fridges': typeof AuthedAdminFridgesIndexRoute
  '/admin/sales': typeof AuthedAdminSalesIndexRoute
  '/f/$fridgeId': typeof AuthedFFridgeIdIndexRoute
  '/master/admins': typeof AuthedMasterAdminsIndexRoute
  '/master/fridges': typeof AuthedMasterFridgesIndexRoute
  '/master/sales': typeof AuthedMasterSalesIndexRoute
  '/f/$fridgeId/product/$productId': typeof AuthedFFridgeIdProductProductIdRoute
  '/f/$fridgeId/sale/$saleId': typeof AuthedFFridgeIdSaleSaleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/admin': typeof AuthedAdminRouteRouteWithChildren
  '/_authed/master': typeof AuthedMasterRouteRouteWithChildren
  '/_authed/account': typeof AuthedAccountRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/admin/': typeof AuthedAdminIndexRoute
  '/_authed/master/': typeof AuthedMasterIndexRoute
  '/_authed/admin/sales/$saleId': typeof AuthedAdminSalesSaleIdRoute
  '/_authed/master/sales/$saleId': typeof AuthedMasterSalesSaleIdRoute
  '/_authed/admin/fridges/': typeof AuthedAdminFridgesIndexRoute
  '/_authed/admin/sales/': typeof AuthedAdminSalesIndexRoute
  '/_authed/f/$fridgeId/': typeof AuthedFFridgeIdIndexRoute
  '/_authed/master/admins/': typeof AuthedMasterAdminsIndexRoute
  '/_authed/master/fridges/': typeof AuthedMasterFridgesIndexRoute
  '/_authed/master/sales/': typeof AuthedMasterSalesIndexRoute
  '/_authed/f/$fridgeId/product/$productId': typeof AuthedFFridgeIdProductProductIdRoute
  '/_authed/f/$fridgeId/sale/$saleId': typeof AuthedFFridgeIdSaleSaleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/master'
    | '/account'
    | '/admin/'
    | '/master/'
    | '/admin/sales/$saleId'
    | '/master/sales/$saleId'
    | '/admin/fridges/'
    | '/admin/sales/'
    | '/f/$fridgeId/'
    | '/master/admins/'
    | '/master/fridges/'
    | '/master/sales/'
    | '/f/$fridgeId/product/$productId'
    | '/f/$fridgeId/sale/$saleId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/account'
    | '/'
    | '/admin'
    | '/master'
    | '/admin/sales/$saleId'
    | '/master/sales/$saleId'
    | '/admin/fridges'
    | '/admin/sales'
    | '/f/$fridgeId'
    | '/master/admins'
    | '/master/fridges'
    | '/master/sales'
    | '/f/$fridgeId/product/$productId'
    | '/f/$fridgeId/sale/$saleId'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/_authed/admin'
    | '/_authed/master'
    | '/_authed/account'
    | '/_authed/'
    | '/_authed/admin/'
    | '/_authed/master/'
    | '/_authed/admin/sales/$saleId'
    | '/_authed/master/sales/$saleId'
    | '/_authed/admin/fridges/'
    | '/_authed/admin/sales/'
    | '/_authed/f/$fridgeId/'
    | '/_authed/master/admins/'
    | '/_authed/master/fridges/'
    | '/_authed/master/sales/'
    | '/_authed/f/$fridgeId/product/$productId'
    | '/_authed/f/$fridgeId/sale/$saleId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/account': {
      id: '/_authed/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthedAccountRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/admin': {
      id: '/_authed/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthedAdminRouteRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/master': {
      id: '/_authed/master'
      path: '/master'
      fullPath: '/master'
      preLoaderRoute: typeof AuthedMasterRouteRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/admin/': {
      id: '/_authed/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthedAdminIndexRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/master/': {
      id: '/_authed/master/'
      path: '/'
      fullPath: '/master/'
      preLoaderRoute: typeof AuthedMasterIndexRouteImport
      parentRoute: typeof AuthedMasterRouteRoute
    }
    '/_authed/admin/fridges/': {
      id: '/_authed/admin/fridges/'
      path: '/fridges'
      fullPath: '/admin/fridges/'
      preLoaderRoute: typeof AuthedAdminFridgesIndexRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/sales/': {
      id: '/_authed/admin/sales/'
      path: '/sales'
      fullPath: '/admin/sales/'
      preLoaderRoute: typeof AuthedAdminSalesIndexRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/sales/$saleId': {
      id: '/_authed/admin/sales/$saleId'
      path: '/sales/$saleId'
      fullPath: '/admin/sales/$saleId'
      preLoaderRoute: typeof AuthedAdminSalesSaleIdRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/f/$fridgeId/': {
      id: '/_authed/f/$fridgeId/'
      path: '/f/$fridgeId'
      fullPath: '/f/$fridgeId/'
      preLoaderRoute: typeof AuthedFFridgeIdIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/master/admins/': {
      id: '/_authed/master/admins/'
      path: '/admins'
      fullPath: '/master/admins/'
      preLoaderRoute: typeof AuthedMasterAdminsIndexRouteImport
      parentRoute: typeof AuthedMasterRouteRoute
    }
    '/_authed/master/fridges/': {
      id: '/_authed/master/fridges/'
      path: '/fridges'
      fullPath: '/master/fridges/'
      preLoaderRoute: typeof AuthedMasterFridgesIndexRouteImport
      parentRoute: typeof AuthedMasterRouteRoute
    }
    '/_authed/master/sales/': {
      id: '/_authed/master/sales/'
      path: '/sales'
      fullPath: '/master/sales/'
      preLoaderRoute: typeof AuthedMasterSalesIndexRouteImport
      parentRoute: typeof AuthedMasterRouteRoute
    }
    '/_authed/master/sales/$saleId': {
      id: '/_authed/master/sales/$saleId'
      path: '/sales/$saleId'
      fullPath: '/master/sales/$saleId'
      preLoaderRoute: typeof AuthedMasterSalesSaleIdRouteImport
      parentRoute: typeof AuthedMasterRouteRoute
    }
    '/_authed/f/$fridgeId/product/$productId': {
      id: '/_authed/f/$fridgeId/product/$productId'
      path: '/f/$fridgeId/product/$productId'
      fullPath: '/f/$fridgeId/product/$productId'
      preLoaderRoute: typeof AuthedFFridgeIdProductProductIdRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/f/$fridgeId/sale/$saleId': {
      id: '/_authed/f/$fridgeId/sale/$saleId'
      path: '/f/$fridgeId/sale/$saleId'
      fullPath: '/f/$fridgeId/sale/$saleId'
      preLoaderRoute: typeof AuthedFFridgeIdSaleSaleIdRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
  }
}

interface AuthedAdminRouteRouteChildren {
  AuthedAdminIndexRoute: typeof AuthedAdminIndexRoute
  AuthedAdminSalesSaleIdRoute: typeof AuthedAdminSalesSaleIdRoute
  AuthedAdminFridgesIndexRoute: typeof AuthedAdminFridgesIndexRoute
  AuthedAdminSalesIndexRoute: typeof AuthedAdminSalesIndexRoute
}

const AuthedAdminRouteRouteChildren: AuthedAdminRouteRouteChildren = {
  AuthedAdminIndexRoute: AuthedAdminIndexRoute,
  AuthedAdminSalesSaleIdRoute: AuthedAdminSalesSaleIdRoute,
  AuthedAdminFridgesIndexRoute: AuthedAdminFridgesIndexRoute,
  AuthedAdminSalesIndexRoute: AuthedAdminSalesIndexRoute,
}

const AuthedAdminRouteRouteWithChildren =
  AuthedAdminRouteRoute._addFileChildren(AuthedAdminRouteRouteChildren)

interface AuthedMasterRouteRouteChildren {
  AuthedMasterIndexRoute: typeof AuthedMasterIndexRoute
  AuthedMasterSalesSaleIdRoute: typeof AuthedMasterSalesSaleIdRoute
  AuthedMasterAdminsIndexRoute: typeof AuthedMasterAdminsIndexRoute
  AuthedMasterFridgesIndexRoute: typeof AuthedMasterFridgesIndexRoute
  AuthedMasterSalesIndexRoute: typeof AuthedMasterSalesIndexRoute
}

const AuthedMasterRouteRouteChildren: AuthedMasterRouteRouteChildren = {
  AuthedMasterIndexRoute: AuthedMasterIndexRoute,
  AuthedMasterSalesSaleIdRoute: AuthedMasterSalesSaleIdRoute,
  AuthedMasterAdminsIndexRoute: AuthedMasterAdminsIndexRoute,
  AuthedMasterFridgesIndexRoute: AuthedMasterFridgesIndexRoute,
  AuthedMasterSalesIndexRoute: AuthedMasterSalesIndexRoute,
}

const AuthedMasterRouteRouteWithChildren =
  AuthedMasterRouteRoute._addFileChildren(AuthedMasterRouteRouteChildren)

interface AuthedRouteRouteChildren {
  AuthedAdminRouteRoute: typeof AuthedAdminRouteRouteWithChildren
  AuthedMasterRouteRoute: typeof AuthedMasterRouteRouteWithChildren
  AuthedAccountRoute: typeof AuthedAccountRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedFFridgeIdIndexRoute: typeof AuthedFFridgeIdIndexRoute
  AuthedFFridgeIdProductProductIdRoute: typeof AuthedFFridgeIdProductProductIdRoute
  AuthedFFridgeIdSaleSaleIdRoute: typeof AuthedFFridgeIdSaleSaleIdRoute
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedAdminRouteRoute: AuthedAdminRouteRouteWithChildren,
  AuthedMasterRouteRoute: AuthedMasterRouteRouteWithChildren,
  AuthedAccountRoute: AuthedAccountRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedFFridgeIdIndexRoute: AuthedFFridgeIdIndexRoute,
  AuthedFFridgeIdProductProductIdRoute: AuthedFFridgeIdProductProductIdRoute,
  AuthedFFridgeIdSaleSaleIdRoute: AuthedFFridgeIdSaleSaleIdRoute,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
