/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteRouteImport } from './routes/_authed/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedAccountRouteImport } from './routes/_authed/account'
import { Route as AuthedFFridgeIdIndexRouteImport } from './routes/_authed/f/$fridgeId/index'
import { Route as AuthedFFridgeIdProductProductIdRouteImport } from './routes/_authed/f/$fridgeId/product.$productId'
import { Route as AuthedFFridgeIdSaleSaleIdRouteImport } from './routes/_authed/f/$fridgeId/sale.$saleId'

const AuthedRouteRoute = AuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedAccountRoute = AuthedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedFFridgeIdIndexRoute = AuthedFFridgeIdIndexRouteImport.update({
  id: '/f/$fridgeId/',
  path: '/f/$fridgeId/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedFFridgeIdProductProductIdRoute =
  AuthedFFridgeIdProductProductIdRouteImport.update({
    id: '/f/$fridgeId/product/$productId',
    path: '/f/$fridgeId/product/$productId',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedFFridgeIdSaleSaleIdRoute =
  AuthedFFridgeIdSaleSaleIdRouteImport.update({
    id: '/f/$fridgeId/sale/$saleId',
    path: '/f/$fridgeId/sale/$saleId',
    getParentRoute: () => AuthedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/account': typeof AuthedAccountRoute
  '/f/$fridgeId/': typeof AuthedFFridgeIdIndexRoute
  '/f/$fridgeId/product/$productId': typeof AuthedFFridgeIdProductProductIdRoute
  '/f/$fridgeId/sale/$saleId': typeof AuthedFFridgeIdSaleSaleIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/account': typeof AuthedAccountRoute
  '/': typeof AuthedIndexRoute
  '/f/$fridgeId': typeof AuthedFFridgeIdIndexRoute
  '/f/$fridgeId/product/$productId': typeof AuthedFFridgeIdProductProductIdRoute
  '/f/$fridgeId/sale/$saleId': typeof AuthedFFridgeIdSaleSaleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/account': typeof AuthedAccountRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/f/$fridgeId/': typeof AuthedFFridgeIdIndexRoute
  '/_authed/f/$fridgeId/product/$productId': typeof AuthedFFridgeIdProductProductIdRoute
  '/_authed/f/$fridgeId/sale/$saleId': typeof AuthedFFridgeIdSaleSaleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/account'
    | '/f/$fridgeId/'
    | '/f/$fridgeId/product/$productId'
    | '/f/$fridgeId/sale/$saleId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/account'
    | '/'
    | '/f/$fridgeId'
    | '/f/$fridgeId/product/$productId'
    | '/f/$fridgeId/sale/$saleId'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/_authed/account'
    | '/_authed/'
    | '/_authed/f/$fridgeId/'
    | '/_authed/f/$fridgeId/product/$productId'
    | '/_authed/f/$fridgeId/sale/$saleId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/account': {
      id: '/_authed/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthedAccountRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/f/$fridgeId/': {
      id: '/_authed/f/$fridgeId/'
      path: '/f/$fridgeId'
      fullPath: '/f/$fridgeId/'
      preLoaderRoute: typeof AuthedFFridgeIdIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/f/$fridgeId/product/$productId': {
      id: '/_authed/f/$fridgeId/product/$productId'
      path: '/f/$fridgeId/product/$productId'
      fullPath: '/f/$fridgeId/product/$productId'
      preLoaderRoute: typeof AuthedFFridgeIdProductProductIdRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/f/$fridgeId/sale/$saleId': {
      id: '/_authed/f/$fridgeId/sale/$saleId'
      path: '/f/$fridgeId/sale/$saleId'
      fullPath: '/f/$fridgeId/sale/$saleId'
      preLoaderRoute: typeof AuthedFFridgeIdSaleSaleIdRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
  }
}

interface AuthedRouteRouteChildren {
  AuthedAccountRoute: typeof AuthedAccountRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedFFridgeIdIndexRoute: typeof AuthedFFridgeIdIndexRoute
  AuthedFFridgeIdProductProductIdRoute: typeof AuthedFFridgeIdProductProductIdRoute
  AuthedFFridgeIdSaleSaleIdRoute: typeof AuthedFFridgeIdSaleSaleIdRoute
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedAccountRoute: AuthedAccountRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedFFridgeIdIndexRoute: AuthedFFridgeIdIndexRoute,
  AuthedFFridgeIdProductProductIdRoute: AuthedFFridgeIdProductProductIdRoute,
  AuthedFFridgeIdSaleSaleIdRoute: AuthedFFridgeIdSaleSaleIdRoute,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
